# Generated by Django 4.2.1 on 2023-05-21 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiobot', '0002_productimage_productimage_max_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='product_images', validators=[django.core.validators.validate_image_file_extension]),
            preserve_default=False,
        ),
    ]
