# Generated by Django 4.2.1 on 2023-05-21 11:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiobot', '0003_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
