# Generated by Django 4.2.1 on 2023-05-21 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiobot', '0004_alter_producttranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pass_message', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiobot.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiobot.tguser')),
            ],
        ),
    ]
